
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${DOCKER_APP_PORT_MAPPING}"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: postgres_container
    ports:
      - "${DOCKER_DATABASE_PORT_MAPPING}"
    environment:
      POSTGRES_DB: ${DATASOURCE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
