logging:
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} %msg%n"

jwt:
  secret: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
  expiration: 36000000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/food_delivery
    username: postgres
    password: 1
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  application:
    name: food-delivery
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
